# Generated by Django 3.2.6 on 2022-05-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220521_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='developer_name',
            new_name='user',
        ),
    ]
